### ISSUE TITLE
This error is thrown every time I join the server, so long as I have data in db.

### ISSUE THREAD

**Issue by svanderweele** [MrPancakers/division-freeroam#12]
TypeError: Cannot read property 'Mother' of undefined
    at Object.player.applyCharacter (D:\RAGEMP\server-files\packages\division-freeroam\charcreator.js:79:42)
    at server.db.query.then (D:\RAGEMP\server-files\packages\division-freeroam\charcreator.js:105:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by MrPancakers** [comment]
I'll contact you about this, can't seem to replicate this.

**Comment by svanderweele** [comment]
I’ll send over the data later on but I doubt it’s relevant. Female was 45
is all I remember but I’m guessing it’s default!

**Comment by svanderweele** [comment]
If this happens to you, make sure your data type in SQL is set to JSON for 'Outfit' field
